baseURL = 'https://vit.ooo/'
defaultContentLanguage  = 'ru'

languageCode = 'ru-ru'
title = 'ООО «вАйТи»'
description = 'Агентство цифровых интеграций'
theme = 'vit'
publishDir = 'docs'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Techs'
pageRef = '/techs'
weight = 20

[[menus.main]]
name = 'Team'
pageRef = '/team'
weight = 30

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 40

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 50

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 60

[[menus.main]]
name = 'Services'
pageRef = '/services'
weight = 70

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.goldmark.parser.attribute]
    block = true
    title = true

    
[permalinks]
#posts = "/:title/:filename"
#services = "/:title/:filename"

